springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  datasource:
    url: jdbc:h2:file:./db/userdb
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    include-stacktrace: never
auth:
  baseUrl: "http://localhost:8080/"
  authorizationEndpoint: "auth/login"
  tokenEndpoint: "auth/token"
  jwksEndpoint: ".well-known/jwks.json"
  allowedRedirects:
    - "http://localhost:3000/"