springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    de:
      zwisler:
        ada: DEBUG
spring:
  datasource:
    url: jdbc:h2:file:./db/userdb
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    include-stacktrace: never
  port: 8090
auth:
  baseUrl: ${BASE_URL}
  authorizationEndpoint: "auth/login"
  tokenEndpoint: "auth/token"
  jwksEndpoint: ".well-known/jwks.json"
  allowedRedirects: ${ALLOWED_REDIRECTS}
  keyPath: "./keys/"